### PR TITLE
Fixed `permission denied` regression

### LINKED ISSUE #228: "permission denied" regression on helm_repo path during `fab install` with 0.15.1
**Describe the bug:**

With 0.15.1, I am seeing an error when I do a `fab install` on a deployment that looks like:

```
INFO[16-07-2019 06:58:04] 👈  Finished install for component: istio-service
INFO[16-07-2019 06:58:04] 👉  Starting install for component: istio-service
INFO[16-07-2019 06:58:04] 👈  Finished install for component: istio-service
INFO[16-07-2019 06:58:05] 🚚  Copying /var/folders/7j/4yvbvdvd7qbcrwddj828lxnh0000gn/T/531b0169-d390-41fe-b42d-d89b50db3a15 => /Users/timothypark/dev/deployment-definition/helm_repos/postgres-operator
Error: open helm_repos/postgres-operator/.git/objects/pack/pack-f573c9b55a327f19aa501a9437f0ee63a9f21975.idx: permission denied
```

This does not occur with 0.15.0

**To Reproduce:**

Not sure if this is broadly reproducible or a race condition that I am running into.

**Expected behavior:**

Able to install without failure.

**Screenshots:**

**Additional context:**

**Desktop (please complete the following information):**

- OS: MacOSX

**Additional context**

### PR DESCRIPTION
**Pull request by evanlouie**
- Fixed an error which would occur if a user attempted to `install` a component which already previously been installed. This was caused do to being unable to overwrite existing files in the installed components `.git` directory. The previously installed component is now deleted prior to copying from the clone cache.
-  General cleanup

fixes #228

### CODE REVIEW

File: core/git.go [hunk 1]
```diff
@@ -199,16 +199,26 @@ func (cache *gitCache) cloneRepo(repo string, commit string, branch string) chan
...
+func (g git) CloneRepo(repo string, commit string, intoPath string, branch string) (err error) {
 	// Clone and get the location of where it was cloned to in tmp
 	result := <-cache.cloneRepo(repo, commit, branch)
 	clonePath := result.get()
 	if result.Error != nil {
 		return result.Error
 	}
 
+	// Remove the into directory if it already exists
+	if err = os.RemoveAll(intoPath); err != nil {
```
Comment (evanlouie) [inline core/git.go]: Important part

File: generators/helm.go [hunk 2]
```diff
@@ -315,6 +315,11 @@ func (hd *helmDownloader) downloadChart(repo, chart, version, into string) (err
 	}
 	hd.mu.Unlock()
 
+	// Remove the into directory if it already exists
+	if err = os.RemoveAll(into); err != nil {
```
Comment (evanlouie) [inline generators/helm.go]: Important part
